apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-kro
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
  - step: kro-run
    functionRef:
      name: function-kro
    input:
      apiVersion: kro.fn.crossplane.io/v1beta1
      kind: ResourceGraph
      resources:
        - id: test
          template:
            apiVersion: apiextensions.crossplane.io/v1beta1
            kind: EnvironmentConfig
            data:
              test: data
